version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DB_HOSTNAME=
      - DB_USERNAME=
      - DB_PASSWORD=
      - DB_DATABASE=
      - DB_PORT=5432
      - NATS_HOST=
      - NATS_PORT=
      - AWS_ACCESS_KEY_ID=
      - AWS_SECRET_ACCESS_KEY=
      - AWS_DEFAULT_REGION=
      - AWS_ENDPOINT_URL=
      - S3_BUCKET=
    volumes:
      - ./src:/src
      - ./tests:/tests