name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build
        run: docker-compose build
  unit-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Unit Tests
        run: docker-compose run --rm --no-deps --entrypoint=pytest app /tests/unit -v
  integration-tests:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run Integration Tests
        run: docker-compose run --rm --no-deps --entrypoint=pytest app /tests/integration -v
